# Generated by Django 3.0.5 on 2020-04-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
