# Generated by Django 3.0.5 on 2020-04-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_score',
            name='score_mean',
        ),
        migrations.AddField(
            model_name='store',
            name='score_mean',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='store_score',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
