# Generated by Django 3.0.5 on 2020-04-27 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20200427_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_score',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='stores.Store'),
        ),
    ]
