# Generated by Django 3.0.5 on 2020-04-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20200427_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_menu',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='store_score',
            old_name='store_id',
            new_name='store',
        ),
    ]
