# Generated by Django 3.0.5 on 2020-04-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20200422_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_menu',
            name='menu_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
