# Generated by Django 3.0.5 on 2020-04-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20200422_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_menu',
            name='menu_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
