# Generated by Django 3.0.5 on 2020-04-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_history',
            name='payment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
