# Generated by Django 3.0.5 on 2020-04-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='kakao_id',
        ),
    ]
