# Generated by Django 3.0.5 on 2020-04-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200422_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='item',
        ),
        migrations.RemoveField(
            model_name='user',
            name='monthly_cost',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price',
        ),
    ]
